### ISSUE TITLE
Quick edit forms for a table of items

### ISSUE THREAD

**Issue by judgej** [ralphjsmit/tall-interactive#23]
This is more a question than an issue.

I have a table of items, and for each item would like a quick-display and quick-edit of those items, that can be used without leaving the table.

For example, a table of products may be shown, and when I click on the `stores` column of a product, a modal form slides in listing the stores the product is located at. Stores can be added and removed in that form, after which the form slides back out of the way and the table of products is still there underneath.

What I'm unclear about, is whether this is a use-case that this plugin is able top support. All the examples I can see seem to show a single form on the page, with a unique ID, and that form can be pulled on when needed. What I don't know is whether that form is rendered with the complete page, or rendered only when it is requested.

There are no examples of data being passed from the event - for example a product ID - to the rendering of the form. So is that something not supported? Obviously the ideal situation, where there could be hundreds of products in a page, is that no edit forms for those products hit the browser until they are actually needed.

Is this how it works, or are all forms constructed and rendered up front whether used or not? Or maybe there is a simple "show a component in a model" package I should be using instead?

**Comment by judgej** [comment]
It's looking like https://github.com/wire-elements/modal may do the job I need - just a modal wrapper for components. It doesn't do the slide-in, which I like, but does nested modals, which is handy.

I'll leave the issue open for now, just in case there is a simple yes/no answer that would be helpful to others.

**Comment by ralphjsmit** [comment]
Hi Jason! Thanks for your question.

It seems like your use case is supported. For example, if you check the following example:

```blade
@foreach (\App\Models\User::get() as $user)
    <x-tall-interactive::modal
        id="edit-user"
        :form="\App\Forms\UserForm::class"
        :model="$user"
    />
@endforeach
```

Instead of users, you will iterate over the products that you have in the list. Then, if you pass it like `:model="$product"`, you can use it to receive it in the mount() method of the form (https://github.com/ralphjsmit/tall-interactive#mounting-the-form):

```php
public Product $user;
public string $x = '';

public function mount(array $params, Product $model): void
{
    $this->product = $model;
    $this->x = $params['x'];
}
                                                                  
public function getFormSchema(): array
{
    return [
         //
    ];
}
```

Alternatively, you can check out this section: https://github.com/ralphjsmit/tall-interactive#reacting-to-events. In that case, you only need a single modal component included.

### Sidenote

As a sidenote, I'm not sure if you aware of Filament (filamentphp.com) (or perhaps you found this plugin via their website). Filament will launch a new major version of all the packages in it's ecosystem in [34 days](https://v3when.com/). That will also include the launch of a new so-called "Actions" package.

The reason I'm saying this is that I'll probably deprecate this package, because the Filament Actions package will do this all, but better. So if you can wait a little over a month, I'd recommend to put a reminder in your agenda and check out the Filament website and the docs about the new package.

Hope that helps!
